name: Deploy to Databricks

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Feature branch to deploy'
        required: true
        default: 'feature/my-feature'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the specified branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        databricks configure --token <<EOF
        ${{ secrets.DATABRICKS_HOST }}
        ${{ secrets.DATABRICKS_TOKEN }}
        EOF

    - name: Create 'release' folder in Workspace
      run: |
        databricks workspace mkdirs /release/${{ github.event.inputs.branch }}

    - name: Upload files to release folder
      run: |
        for file in $(find . -name "*.py" -o -name "*.dbc" -o -name "*.ipynb"); do
          workspace_path="/release/${{ github.event.inputs.branch }}/${file#./}"
          echo "Uploading $file to $workspace_path"
          databricks workspace import "$file" "$workspace_path" --format AUTO --overwrite
        done
