name: Deploy Notebooks to Databricks

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Feature branch to deploy'
        required: true
        default: 'feature/my-feature'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the specified branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Install Databricks CLI
      run: pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        mkdir -p ~/.databricks
        echo "[DEFAULT]" > ~/.databricks/config
        echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databricks/config
        echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databricks/config

    - name: Create release folder
      run: |
        databricks workspace mkdirs /release/${{ github.event.inputs.branch }}

    - name: Upload .ipynb notebooks to release folder
      run: |
        find . -name "*.ipynb" | while read file; do
          rel_path="${file#./}"  # remove leading ./
          workspace_path="/release/${{ github.event.inputs.branch }}/$rel_path"
          echo "Uploading $file to $workspace_path"
          databricks workspace import "$file" "$workspace_path" --format JUPYTER --overwrite
        done
