name: SIT Deployment

on:
  pull_request:
    branches:
      - sit_branch
      

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DATABRICKS_SIT_HOST }}
          ${{ secrets.DATABRICKS_SIT_TOKEN }}
          EOF
      - name: Create release folder
        run: |
          databricks workspace mkdirs /release/
    
      - name: Upload files to /Workspace/release
        run: |
          databricks workspace mkdirs /release
          databricks workspace import_dir . /release --overwrite
